### ISSUE TITLE
Why are some formatting classes enums?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#112]
Some (package-local) formatting classes like ``ExponentFormatter``, ``InternalFormatter`` or ``FormatConverter`` are declared as ``enum`` but they do not expose constants of type enum.
For a "singleton" behavior and a single ``INSTANCE`` they don't require the overhead of an enum.

**Comment by otaviojava** [comment]
"This approach is functionally equivalent to the public field approach, except that it is more concise, provides the serialization machinery for free, and provides an ironclad guarantee against multiple instantiation, even in the face of sophisticated serialization or reflection attacks. While this approach has yet to be widely adopted, a single-element enum type is the best way to implement a singleton."
 Effective Java

**Comment by keilw** [comment]
It's not very commonly used though. Which chapter of Effective Java do you mean?
Especially for package-local elements, we may keep it that way.

**Comment by desruisseaux** [comment]
I would support making Formatters ordinary classes instead of enums. I think that a class should be an enum only if it is conceptually an enumeration, which I think is not the case of Formatters. But as Werner said, if those formatters are package-private it may not be a critical issue.

**Comment by keilw** [comment]
Those are not even real formatters, mainly helpers;-) The enum argument however backs the original intent of the issue. Will reopen it. Thanks for the input.

**Comment by keilw** [comment]
Most of these methods could simply be static, package local.

**Comment by otaviojava** [comment]
@keilw the book is effective java from joshua bloch.

**Comment by keilw** [comment]
I had that book, not sure if I still have it, but there are also online versions. Regardless, what Martin also said, even in a package-local helper class using an enum with its name, ordinal or values() collection feels like an overhead for areas where you don't use any of these or enumerate a list of public constants. Reduced it to 2 helper classes, since methods of the 3rd are nothing but private internals of now ``EBNFHelper``.

**Comment by desruisseaux** [comment]
I also have this book and like the vast majority of it. But this particular recommendation of Effective Java seems to be the most controversial point of the book. An organizer of a Java user group cited this exact chapter as an example of why we should not take everything in this book as true. I must admit that when he told me about this chapter, I couldn't believed that Joshua wrote that until he put me the text under my nose.

**Comment by keilw** [comment]
Good point. Similar to other cases like "everything must be a final class" some patterns and principles should not be taken "religiously". Josh also recommended some particular naming conventions like ``valueOf()`` and ``getInstance()`` for certain situations and was then seemingly the first to break these by using a short ``of()`` version in https://docs.oracle.com/javase/7/docs/api/java/util/EnumSet.html ;-)

**Comment by otaviojava** [comment]
Ok. I'll remove it.

**Comment by keilw** [comment]
It's already changed and 2 of the mentioned classes merged into one.

**Comment by otaviojava** [comment]
Ok, Thank you.
