### ISSUE TITLE
uom-se doesn't compile with JDK 8 (update 73,74)

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-se#115]
I'm trying to use the uom-se with JDK 8 but I'm facing some problem while compiling. I've seen similar problems were already raised and solved before but I could not find the cause of why it is still not compiling.

I'm really not sure whether it is a problem on my local machine or something due to the JDK 1.8.

Seems to be located in the Units.java class. 

See attached maven log. 
[mavenLog.txt](https://github.com/unitsofmeasurement/uom-se/files/181837/mavenLog.txt)

**Comment by keilw** [comment]
Is it OpenJDK or Oracle JDK?

**Comment by keilw** [comment]
Your test build does not use Update 73/74 or is it an older file? I see Library/Java/JavaVirtualMachines/jdk1.8.0_31. Circle CI seems to use JDK 8 without a notable upgrade. If this continues, we might explore using other systems like TravisCI, but I regularly build with Java SE 8, possibly 60. Do you have a maven log from that? Older versions like 1.8.0_31 probably contained bugs Oracle fixed in the meantime.

**Comment by lfoppiano** [comment]
OK, I've checked and double checked and I've missed the path to the update31, sorry. I've noticed that I have several version of the JDK 8, but somehow maven is picking up the update 31, thought java -version gives me the latest version. 
I double check and come back to you.

**Comment by keilw** [comment]
Yes, please do, if you face a similar error with SP 73/74, let us know and update here. I'll keep it open for the feedback. Probably also do a cross-check myself. thanks for the clarification.

**Comment by lfoppiano** [comment]
OK, it was a mistake in the configuration, so I was using the wrong JDK. Only my local maven was using the update 31, so I overlooked it. No problem to build with update 74.

**Comment by keilw** [comment]
Thanks, closing it then. Let's hope it doesn't haunt us again with SE 9? ;-)

**Comment by lfoppiano** [comment]
I notice that the 0.9-SNAPSHOT does not compile because one of the classes doesn't override the method compareTo. 

See log: 
`
ERROR] /Users/lfoppiano/development/inria/unit-normalization/uom-se/src/main/java/tec/uom/se/internal/PriorityAwareServiceProvider.java:[51,8] tec.uom.se.internal.PriorityAwareServiceProvider is not abstract and does not override abstract method compareTo(javax.measure.spi.ServiceProvider) in java.lang.Comparable
[INFO] 1 error
`

Is not a problem to fix it, but I'm wondering how come the CI did not spot it. Perhaps am I doing something wrong myself?

**Comment by keilw** [comment]
Unlike Jenkins Circle-CI (at least in the Public/Free edition) does not have sophisticated down-stream build triggers. So if uom-se changes in Git, that job is built, but a change in unit-api won't trigger it. Will fix it thanks, we made some changes in the API and the EG also discusses a few other changes in bootstrapping, but they won´t to into master before everything works in the design branch first.

**Comment by lfoppiano** [comment]
I'm going to implement the travis build for my forked version, just to be sure it will be consistent. I could also try cicle-ci to see something new :) 
I could share the configuration file with you once it works for me if you like.

**Comment by keilw** [comment]
No it's there, and if you forked it, please either pull everything or delete the fork. uom-se on master correctly implements Comparable and builds OK.

**Comment by lfoppiano** [comment]
Indeed, you're right. Sorry again.

**Comment by lfoppiano** [comment]
By the way, this morning I've created the same ticket in jira before realizing that uom-se had it's own issue tracker in github. Should be closed. 

It's here: https://java.net/jira/browse/UNITSOFMEASUREMENT-187

**Comment by keilw** [comment]
also closed, thanks
