### ISSUE TITLE
Non SI Units (e.g. Acidity - pH)

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-se#126]
Hi, 
   we need to be able to recognize the unit pH. Right now the SimpleUnitFormat understands only pH as picon Henry.  I think we would need to have different parser for different systems (Imperial, metric, etc). What do you think? 

In general I've noticed some commented code referring to a class called NonUnit.java: 
```
    // DEFAULT.label(NonUnits.LAMBERT, "La");
    // DEFAULT.label(NonUnits.FOOT, "ft");
    // DEFAULT.label(NonUnits.FOOT_SURVEY_US, "foot_survey_us");
    // DEFAULT.label(NonUnits.YARD, "yd");
    // DEFAULT.label(NonUnits.INCH, "in");
    // DEFAULT.label(NonUnits.MILE, "mi");
    // DEFAULT.label(NonUnits.NAUTICAL_MILE, "nmi")
```

Is this just some old code or is this the way should be implemented, but it has not yet been done? 
We might want to add all these units back to uom-se ;)

Thanks
Luca

**Comment by keilw** [comment]
Could you please file it here: https://github.com/unitsofmeasurement/uom-systems/issues
Some of the "NonUnits" previously "NonSI" also belong there. They are left at least in uom-se as a reference in case any of them are not in either `US`, `UCUM` or similar. Indeed, especially the module for UCUM defines its own special `UnitFormat` implementations for parsing and formatting. Any module with a similar need could do that.

Will close it, as it doesn't need addressing in the implementation.

Thanks,
Werner

**Comment by lfoppiano** [comment]
OK, makes sense. 
I'm glad I don't have to implement the whole parsing for nonSI units!! :-)

**Comment by keilw** [comment]
No, especially UCUM tries to cover all possible units it contains with a separate unique key. Therefore "pico Henry" and "pH" if UCUM covers it could be told apart. It seems the system where it does make sense to include would be ISO80000: https://webstore.iec.ch/preview/info_iso80000-9%7Bed1.0%7Den.pdf

**Comment by lfoppiano** [comment]
OK, I open the issue on the other project and we can continue to discuss there, cause I have additional questions ;)
