### ISSUE TITLE
Infinite loop converting from Radians to Degrees

### ISSUE THREAD

**Issue by krevelen** [unitsofmeasurement/uom-se#131]
Both these conversions loop infinitely, somewhere during execution of `tec.uom.se.function.PiMultiplierConverter.Pi#arccot(BigDecimal, int)`:

- `Quantities.getQuantity( BigDecimal.ONE, Units.DEGREE_ANGLE ).to( Units.RADIAN )`
- `Quantities.getQuantity( BigDecimal.ONE, Units.RADIAN ).to( Units.DEGREE_ANGLE )`

Perhaps I should create my own `DEGREE_ANGLE` unit with a `PiMultiplierConverter` based on e.g. [Apfloat Pi calculators](http://www.apfloat.org/apfloat_java/docs/org/apfloat/samples/Pi.html), or do you have other suggestions?

**Comment by keilw** [comment]
Just working on it, looks like I found a fix that works. RI is unaffected, currently this operation only exists for  Java SE, it may not work with Java ME/Double.

**Comment by keilw** [comment]
Done, but please note, units "accepted with SI" like DEGREE_RADIAN exist in SI-units, that's why they are not in the RI, so they'll be removed from UOM-SE in an upcoming version for consistency.
