### ISSUE TITLE
Remove dependency on javax.annotation

### ISSUE THREAD

**Issue by kaikreuzer** [unitsofmeasurement/uom-se#134]
I just tried to use oum-se within an Eclipse project, but when [adding it to my target platform](https://github.com/eclipse/smarthome/pull/2722#issue-198128481), I noticed that it has a dependency on javax.annotation 1.3. As this is not available in Eclipse Orbit, there is no easy way for me to use uom-se :-(

Scanning the code, I noticed that this lib only seems to be used [in two places](https://github.com/unitsofmeasurement/uom-se/search?l=Java&q=%22javax.annotation%22&utf8=%E2%9C%93), one of which is marked as "TODO this should no longer be necessary". I therefore wonder, if it would be possible to completely get rid off this dependency?

**Comment by keilw** [comment]
Hi, I think it was more or less part of earlier Service resolution similar to JSR 354. We redesigned and refactored the ServiceProvider which now has a priority int value on the API level. So while it is still possible to add further more fine grained priority it is not a mandatory requirement for the implementation or need to pass the TCK. Why is that JSR not in Orbit, is there a license issue with it?

**Comment by keilw** [comment]
It would be part of a 1.0.3 update release. I assume, when a CQ for the impl is approved, it allows immediate minor updates like that also to enter Orbit?;-)

**Comment by kaikreuzer** [comment]
> Why is that JSR not in Orbit, is there a license issue with it?

There is only version 1.1.0 and I do not want to take any efforts in getting 1.3.0 approved, if not needed. Anyhow, I think the less dependencies uom-se has, the better. I would create a diff-CQ request for version 1.0.3. yes.

**Comment by keilw** [comment]
I think we can do without it. Should certain modules need it, they could still use the annotations, but in the core implementation we can spare it.

**Comment by kaikreuzer** [comment]
@keilw Any chance to do a 1.0.3 anytime soon?

**Comment by keilw** [comment]
Yes, as I fixing https://github.com/unitsofmeasurement/uom-systems/issues/51 required an update of the uom-se formatter, I can do so right now.

**Comment by keilw** [comment]
I try to address https://github.com/unitsofmeasurement/uom-se/issues/135 if I can and wrap up a 1.0.3 then.
