### ISSUE TITLE
Cannot parse simple units with SimpleUnitFormat - Exception

### ISSUE THREAD

**Issue by johannnnnnnn** [unitsofmeasurement/uom-se#140]
I'm using SimpleUnitFormat (uom-se 1.0.3) for parsing and cannot parse simple units like '1/m' or '1/kg' or '1/l' or .... . 

I get a ParserException with message 'unexpected token 8' what does this mean ? 

Should SimpleUnitFormat be abel to parse these units ?

The statements are:
ServiceProvider.current().getUnitFormatService().getUnitFormat().parse("1/m");
ServiceProvider.current().getUnitFormatService().getUnitFormat().parse("1/kg");
ServiceProvider.current().getUnitFormatService().getUnitFormat().parse("1/l");

Thx for answer

**Comment by keilw** [comment]
Will check it out. Did you also try the 1.0.4-SNAPSHOT? And what are the units you're trying to model that way?

**Comment by johannnnnnnn** [comment]
The units are all written by a device that measures parameter and writes measurement values and units to a file. We want to import the file and have to parse the units. For example the unit '1/l' is used by a parameter that counts cells per litre (or milli litre or micro litre).

I tried 1.0.4 SNAPSHOT, it doesn't work here too.

**Comment by keilw** [comment]
Will have to check if the operation would be possible, but in either case taking `AbstractUnit.ONE `as a substitute for about anything like `CEL `seems not quite so good either. 
https://github.com/unitsofmeasurement/uom-domain/blob/master/health/health/src/main/java/tec/uom/domain/health/unit/Health.java in uom-domain has some good examples. Leaving aside, that `BPM ` is actually a bit more versatile (e.g. also works for Music) the operation "BEAT/min" shows  how you may probably have to introduce units of your own like `CEL `along the lines of https://github.com/unitsofmeasurement/uom-domain/tree/master/health/health-api/src/main/java/tec/uom/domain/health. It could also be enough to declare a `Dimensionless ` unit if you want to avoid your own quantities, but you should not tweak ONE for such cases. I doubt "1/min" would have worked in the BPM case either.

**Comment by keilw** [comment]
At the moment `SimpleUnitFormat `cannot support parsing units like "1/m" or similar. 
It does work using other more sophisticated implementations e.g. `EBNFUnitFormat`. 

Please use
  ```
EBNFUnitFormat.getInstance().parse("1/m");
EBNFUnitFormat.getInstance().parse("1/kg");
EBNFUnitFormat.getInstance().parse("1/l");
  ```
