### ISSUE TITLE
Question: how to configure UoM to use own UnitFormat

### ISSUE THREAD

**Issue by johannnnnnnn** [unitsofmeasurement/uom-se#141]
Is there anywhere an example how to configure units of measurement, to use my own unit format (e.g. instead of SimpleUnitFormat or other predefined) ?

**Comment by keilw** [comment]
So far we only have this for the RI https://github.com/unitsofmeasurement/unit-ri-userguide, but it could be extended or cloned into a similar GitBook about other implementations or uom-se. While SE has a few extra options, especially `Locale` when formatting, the general idea seems similar to both. Would you be able to help with such chapter?

**Comment by keilw** [comment]
I saw https://github.com/unitsofmeasurement/unit-ri-userguide/blob/master/formatting.md could indeed use some help. I created https://github.com/unitsofmeasurement/unit-ri-userguide/issues/2. Feel free to add more specific tickets on a particular aspect like `UnitFormat` if you want. Please start there if you can, it is no problem copying relevant parts over to a new SE-specific repo.

**Comment by keilw** [comment]
Also created https://github.com/unitsofmeasurement/uom-guide/issues/1 in a general UoM Guide Book. Will close this here.
