### ISSUE TITLE
SymbolMap.getPrefix doesn't work as expected

### ISSUE THREAD

**Issue by johannnnnnnn** [unitsofmeasurement/uom-se#143]
Maybe I found a bug in class **SymbolMap**, the following method
MetricPrefix getPrefix(String symbol)  returns DECI for symbol='dag', but should be DEKA.

The problem is the if statement in the third line.
` if (symbol.startsWith(pfSymbol)) ` is true for pfSymbol='d'
 
`public MetricPrefix getPrefix(String symbol) {`
`for (String pfSymbol : symbolToPrefix.keySet()) {`
 **`if (symbol.startsWith(pfSymbol)) {`**
 `return (MetricPrefix) symbolToPrefix.get(pfSymbol);`
`...`

**Comment by keilw** [comment]
The basic problem is `DEKA` has no abbreviation of "dag" but just "da". If you observed that `DECI` is returned, we have to investigate, because I would expect the correct behavior either to return null or an exception if nothing can be found.

**Comment by johannnnnnnn** [comment]
DECI is returned for ALL Units starting with 'da' ...  dekagramm 'dag' is only a sample which I used for debugging.

**Comment by johannnnnnnn** [comment]
The impact is, that `EBNFUnitFormat.getInstance().parse("dag")` throw a TokenException. This was my problem and why i started debugging.

**Comment by keilw** [comment]
At the moment prefixes like `MetricPrefix` have no concept of "alias" like e.g. UnitFormat does (not at the API level, it could be a possible improvement in the future, but works in `AbstractUnitFormat`) 
"dag" would actually mean "Dekagram", so substituting "da" with "dag" could lead to problems when you combine the prefix with certain units.

**Comment by johannnnnnnn** [comment]
I did not substitute 'da' with 'dag'.
'dag' is my unit
and 'da' is my prefix

**Comment by keilw** [comment]
I se, so is dag the result of the operation or would `DEKA(DAG)` result in something like "dadag"?!

**Comment by keilw** [comment]
If it is possible to share a snipped or attach a working piece of code (either class with `main() `or JUnit) that would be highly appreciated and speed up analysis (if you can share anything without exposing what you work on of course;-)

**Comment by johannnnnnnn** [comment]
[UoMTest.zip](https://github.com/unitsofmeasurement/uom-se/files/796533/UoMTest.zip)
I uploaded a class with 2 tests.

**Comment by keilw** [comment]
I fixed this with a bit of "Lambda" magic sorting. Thanks for raising it. Will check the other issues to get 1.0.4 out by the end of the month (maybe even Monday)

**Comment by johannnnnnnn** [comment]
Thx, works great now.
