### ISSUE TITLE
Fix MICRO symbol in pt locale

### ISSUE THREAD

**Issue by magnonasc** [unitsofmeasurement/uom-se#150]
For some reason the `MICRO` symbol used on the pt locale was `mu` instead of the symbol itself `µ`, and it made a test fail for me.

What's the actual reason for having this line on pt properties?
`tec.uom.se.unit.MetricPrefix.MICRO    = µ`

**Comment by keilw** [comment]
If you get the pt locale by mistake, that should be explored. Hopefully the ROOT locale does not have this side-effect?

**Comment by magnonasc** [comment]
hahaha' no, it's my default locale, the code `getDefault()` worked perfectly ;)
And `ROOT` locale is an empty one, it's like `getLocale("")` and it might be used when the default resource might be retrieved i.e., `messages.properties` and not `messages_en.properties` or `messages_pt.properties`.

**Comment by keilw** [comment]
Thanks, it seems to work at least according to all tests. I also used ROOT in the actual `EBNFUnitFormat` not just the test classes.

**Comment by magnonasc** [comment]
In fact we need to use `ROOT` if we want the default resource, we **should never** test things using `getDefault()` locale because the result of the test will depend on which machine you're running them on, it would make you lose a lot of cases for your tests, and this is a bad thing because the _unit tests should test **all the possible cases**_.. So if you want to test a localized resources, you need to use each one of them, including `ROOT` and excluding `getDefault()`.

It's just keep in mind: _`getDefault()` is good on the api and on the programs using the api, but never in the tests_.

**Comment by keilw** [comment]
Since getDefault() could be German or French in some cases, it is good to use ROOT. Thanks for spotting. There is very little on LocalUnitFormat, but we hope to also get more on that. Unlike `EBNFUnitFormat` there the default Locale is still used.
