### ISSUE TITLE
Question: Is this going to be included in JDK 9?

### ISSUE THREAD

**Issue by zjuhasz** [unitsofmeasurement/uom-se#161]
I tried searching through the pre-release documentation for openjdk 9 and couldn't find anything for this library. Is it planned for this to be included in openjdk9 when it is released?

**Comment by desruisseaux** [comment]
No, `javax.measure` API is not planed for inclusion in JDK9 as far as I know. I'm not aware of discussion for inclusion in future JDK neither, but Werner would known better. Anyway, I think it is good for any library to first get a little bit of maturity outside the JDK.

**Comment by keilw** [comment]
Thanks @desruisseaux for your answer. It is correct. At the moment JDK9 has enough problems to solve with its "Jigsaw" modularity. There are OpenJDK projects like http://openjdk.java.net/projects/kona/ which I also mentioned again during a current Java ME/Embedded WG discussion led by fellow Spec Lead @leomrlima. However the outcome of this Java Embedded WG is still uncertain. And to what extent Oracle or others will offer Java ME 9 Embedded or something similar is not clear at this point. 
uom-se has become the preferred implementation of JSR 363. Eclipse approved it and projects like SmartHome, UOMo or others use it or migrate from earlier JSR 275 based components. PCP Parfait also uses uom-se as the preferred implementation and its key contributor @natoscott helped offer RPMs for Linux: https://bintray.com/unitsofmeasurement/rpm.  In some Linux distributions that have PCP and Parfait pre-installed, you may even find JSR 363 out of the box, too. So if Oracle or the OpenJDK team were to leverage "vertical" modules they will certainly use JSR 363 or 354 or others to come (Image Recognition is a hot candidate in the AI space) 
And during a recent JUG Meeting in Austin, both Brian Goetz and George Saab were present and applauded my vision of "purpose driven" extension modules on top of Java SE 9 or maybe some Embedded variant (ME or SE) for the IoT space. 
I hope that answers your question? Stay tuned for more or use the Maven repositories, RPM or Eclipse P2 repositories on https://bintray.com/unitsofmeasurement and MavenCentral right now ;-)

**Comment by keilw** [comment]
@zjuhasz If this answers your question, feel free to close it or let us know if you want to know more.

**Comment by zjuhasz** [comment]
I mostly understand, thanks for the info. I was asking because I am writing a Kotlin extensions library for uom and I was wondering if I should wait until there is something officially released in the JDK or publish it now with a dependency on uom-se. Given your answer I think I will just publish it now / soon. When I do publish what is the best way for me to share it with you all? Should I post another question issue with a request for people to review it or is there a preferred way? Directly email it perhaps?

**Comment by keilw** [comment]
You are more than happy to contribute Kotlin support along the lines of what JSR 354 got in https://github.com/JavaMoney/javamoney-shelter/tree/master/kotlin-support.

We call the Shelter "Spaces" here: https://github.com/unitsofmeasurement/uom-spaces
An early approach to Groovy support exists. If you want to share your library, please raise an issue there and I'm happy to create a new space. This could be awesome to hack on for the recently founded Kotlin User Group in Düsseldorf: https://www.meetup.com/Dusseldorf-Kotlin-Meetup/ and both JSR 354 and 363 have great value on Android, so Kotlin support would help there, too.
