### ISSUE TITLE
Same Units considered different

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#164]
Similar to https://github.com/unitsofmeasurement/uom-se/issues/156 for quantities
```
assertEquals(MICRO(GRAM), GRAM.divide(1000000));
```
works, but  using nested operations
```
assertEquals(MICRO(GRAM), GRAM.divide(1000).divide(1000));
```
fails. Despite two divisions by `1k` have the same result as dividing by `1 Mio`.

**Comment by keilw** [comment]
Somewhat related to https://github.com/unitsofmeasurement/uom-systems/issues/108. A solution for this issue could benefit https://github.com/unitsofmeasurement/uom-systems/issues/108 for UCUM or other systems.

**Comment by keilw** [comment]
The solution for https://github.com/unitsofmeasurement/uom-systems/issues/111 looks helpful as it results e.g. for UCUM.LITER and UCUM.LITER_DM3 in equal converters.

**Comment by keilw** [comment]
`AbstractUnit` uses `equals()` a lot internally comparing units to another, especially when you call something like `unit1.getConverterTo(unit2).equals(unit2.getConverterTo(unit1)`.  Therefore using it to assist e.g. `unit1.equals(unit2)` is impossible because it leads to an infinite circular call and `StackOverflowException`.  Taking `equals()` out of all these methods does not look feasible either, it makes them work as they do. 

There are API specific methods like `isCompatible(Unit<?> that)` so at the moment the only reliable solution is adding  `public boolean isEquivalentOf(Unit<Q> that)` similar to the one already offered by `ComparableQuantity`. Although a certain combination of operations may be considered "equal" the result should always by definition be "equivalent". https://english.stackexchange.com/questions/317782/equal-vs-equivalent-finer-differences-in-meaning-and-usage-in-4-distinct-scena/317792 provides good answers to how they differ. And AbstractUnit already states, all conversions between physical units should be `symmetric`. Therefore the results are `equivalent`, but not necessarily `equal`. 
The JDK standard method `clone()` is described in a similar way:
http://docs.oracle.com/javase/6/docs/api/java/lang/Object.html#clone%28%29

>  While it is typically the case that:
>   `x.clone().equals(x)`
>  will be true, this is not an absolute requirement.

**Comment by andi-huber** [comment]
Other than testing, what are good use-cases why someone would want to check, whether 2 Units are equal?

My point is: 
If its hard to specify what we mean by 2 Units are equal, then its also hard for users to understand. So why do we try to implement such functionality?
