### ISSUE TITLE
[Bug] Unit conversion

### ISSUE THREAD

**Issue by mwiesiolek** [unitsofmeasurement/uom-se#166]
Hi,

I've encoutered an issue while converting units. The code that I am executing looks as following:

```
Quantity result = ((Quantity) Quantities.getQuantity(20.0, TONNE.multiply(CELSIUS))).to(TONNE.multiply(KELVIN));

```

The error message that I receive is:

```
java.lang.UnsupportedOperationException: ℃ is non-linear, cannot convert
	at tec.uom.se.unit.ProductUnit.getSystemConverter(ProductUnit.java:324)
	at tec.uom.se.AbstractUnit.getConverterTo(AbstractUnit.java:289)
	at tec.uom.se.AbstractQuantity.to(AbstractQuantity.java:181)
	at tec.uom.se.AbstractQuantity.to(AbstractQuantity.java:110)
```

My dependencies versions are:

```
    compile("tec.uom:uom-se:1.0.7")
    compile("tec.uom.lib:uom-lib:1.0.2")
    compile("systems.uom:systems-common-java8:0.7.1")
```

Thanks in advance for helping/fixing it

Regards,
Maks

**Comment by desruisseaux** [comment]
This may not help this issue, but I take this opportunity for pointing to other problems:

1. The error message is misleading, as it suggests that the °C unit is non-linear. I don't think it make sense to said that a unit is linear or non-linear. The **conversion** between two units may be linear or not, but not the unit itself.
2. I think that the current definition of `UnitConverter.isLinear()` in current API is wrong, as it violates the usual mathematical definition of a linear function. A function of the form y=ax+b **is linear**, but `UnitConverter.isLinear()` wrongly said the opposite. `isScale()` would have been a better name.

**Comment by keilw** [comment]
@desruisseaux Could you please propose such improvements or suggestions to https://github.com/unitsofmeasurement/unit-api/issues for future versions of the API. As the JSR is final, any change would have to be carefully considered, e.g. deprecating one and pointing to a new method. Then 2 or 3 major versions later it could be dropped, but backward-compatibility as everywhere in Java is very important.

**Comment by keilw** [comment]
@mwiesiolek Celsius is a "Special Unit" as the UCUM specification calls it: http://unitsofmeasure.org/ucum.html#section-Special-Units-on-non-ratio-Scales
Operations on Temperature units are very limited. If this operation is prevented in UCUM (try e.g. Eclipse UOMo https://github.com/eclipse/uomo or other "dynamic" UCUM implementations based on `ucum-essence.xml`) it also must not work in more statically typed unit libraries.

**Comment by desruisseaux** [comment]
Indeed, the UnitConverter.isLinear() is a separated issue. It already has its issue: https://github.com/unitsofmeasurement/unit-api/issues/39

But on the implementation side, the error message cited in this issue also need to be fixed. "Linear" in the mathematical sense does not apply to units - it applies to unit conversions. The cases where I have seen "linear units" so far were meaning "units of length".

**Comment by keilw** [comment]
Could you do that or propose a PR for it here? Assuming the RI has a similar message, either both PRs or it can easily be back-ported there.

**Comment by desruisseaux** [comment]
If we know the target unit, an alternative could be _"The conversion from °C to Foo is non-linear"_. However if "linear" here was in the sense of `UnitConverter.isLinear()` current javadoc, then something like _"The conversion from °C to Foo is not a ratio"_ may be more accurate.

**Comment by keilw** [comment]
I suppose in a place like `tec.uom.se.AbstractUnit.getConverterTo(AbstractUnit.java:289)` we should know the target unit.
