### ISSUE TITLE
Unit of Time.class

### ISSUE THREAD

**Issue by njenwei** [unitsofmeasurement/uom-se#168]
Is it intentional for the unit of Time.class to be put in the map twice, leading it to be of unit DAY:

`public static final Unit<Time> SECOND = addUnit(new BaseUnit<>("s", QuantityDimension.TIME), Time.class);`
 
`public static final Unit<Time> DAY = addUnit(new TransformedUnit<>("d", SECOND, SECOND, new RationalConverter(24 * 60 * 60, 1)), Time.class);`
 
whereas in the RI version, SECOND is the unit of Time.class

**Comment by keilw** [comment]
Thanks for spotting that. It overlapped the SECOND unit in this case, so you're right, the addition by class should only been done once per quantity. Just fixed in master, will be included in 1.0.8.
