### ISSUE TITLE
AngularSpeed and AngularAcceleration Quantity Support

### ISSUE THREAD

**Issue by AustinShalit** [unitsofmeasurement/uom-se#170]
I think it would be cool if the library supported AngularSpeed and AngularAcceleration quantities in a future release.

**Comment by keilw** [comment]
For derived SI units, please have a look at https://github.com/unitsofmeasurement/si-units and if they are not in the quantity module yet, propose them under https://github.com/unitsofmeasurement/si-units/issues. For all other units and quantities https://github.com/unitsofmeasurement/uom-systems and https://github.com/unitsofmeasurement/uom-systems/issues is the right place. Thanks.
