### ISSUE TITLE
EBNFFormatTest and *ComparableQuantityTest failing

### ISSUE THREAD

**Issue by Pr0methean** [unitsofmeasurement/uom-se#175]
On openjdk-8-jdk (Ubuntu Xenial), when I download and mvn test a clean branch at https://github.com/unitsofmeasurement/uom-se/commit/1c1c1c1d2a530b6cd4bc0194b3a7051f9e06c9f9 I get:
```
[ERROR] Failures: 
[ERROR]   EBNFFormatTest.testParseInverseKg:80 expected:<[1/kg]> but was:<[one]>
[ERROR]   EBNFFormatTest.testParseInverseL:86 expected:<[1/l]> but was:<[one]>
[ERROR]   EBNFFormatTest.testParseInverseM:74 expected:<[1/m]> but was:<[one]>
[ERROR]   DecimalComparableQuantityTest.divideOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   DecimalComparableQuantityTest.multiplyOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   DoubleComparableQuantityTest.divideOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   DoubleComparableQuantityTest.multiplyOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   NumberComparableQuantityTest.divideOperationsExceptionTest Expected exception: java.lang.ClassCastException
[ERROR]   NumberComparableQuantityTest.multiplyOperationsExceptionTest Expected exception: java.lang.ClassCastException
```

**Comment by keilw** [comment]
That's odd, because https://circleci.com/gh/unitsofmeasurement/uom-se/303 and the entire CI build runs on Ubuntu, but it seems to use Oracle JDK rather than OpenJDK. We saw one or the other issue with OpenJDK earlier. Could you try Oracle JDK? If it works there it can only be a bug in OpenJDK.

**Comment by keilw** [comment]
Trying to run it with OpenJDK on an Ubuntu 16 VM, but Maven misbehaves. Somehow the timestamp of plugins to install does not match that of the VM but I try it with relevant M2 repo content from my host system. If that works, we'll see if I can reproduce it or it builds fine even on OpenJDK.

**Comment by keilw** [comment]
I cloned the master of uom-se on the Ubuntu 16.10 VM after installing OpenJDK and mvn test works fine.

[WARNING] Tests run: 375, Failures: 0, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.014 s
[INFO] Finished at: 2017-06-27T22:14:02+02:00
[INFO] Final Memory: 26M/66M
[INFO] ------------------------------------------------------------------------
osboxes@osboxes:~/git/uom-se$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.10.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

So can't reproduce I'm afraid.

**Comment by Pr0methean** [comment]
Reproduced successfully on Oracle JDK 8, in this publicly-copyable VM: https://ide.c9.io/pr0methean/uom-se-oracletest
