### ISSUE TITLE
How to get the dimension class of a ProductUnit?

### ISSUE THREAD

**Issue by Pr0methean** [unitsofmeasurement/uom-se#179]
I'm trying to finish PR #178 and use asType() to troubleshoot the failing test cases. How do I obtain an AbstractUnit's dimension as a Class<? extends Quantity> such as Mass.class or Length.class, i.e. recover the type parameter Q? Will I have to add a reverse of the hash map in AbstractSystemOfUnits? Also, what happens if the dimension is one for which no interface exists in javax.measure.quantity, such as Duration squared -- can asType still be used in that case?

**Comment by keilw** [comment]
I'm afraid that's not possible in Java till Reified Generics in a similar way as C# are offered. Brian Goetz hinted, it may come at some point, but not sure if Java 10 or later. Don't think we tried an interface that does not extend `Quantity`, it does not have to be in the API package, but it has to extend `Quantity`. You likely get an exception.

**Comment by keilw** [comment]
`AbstractUnit` has a protected method `getActualType()` but you can see from the `testReturnedClass()` method, all this returns for a `Length` unit is `java.lang.reflect.TypeVariable<D>`.
