### ISSUE TITLE
toString() method of TransformedUnit does not seem to work as intended

### ISSUE THREAD

**Issue by cleberecht** [unitsofmeasurement/uom-se#188]
I am using uom-se 1.0.8.

The Unit [Angstroem](https://de.wikipedia.org/wiki/%C3%85ngstr%C3%B6m_(Einheit)) occurs frequently in molecular biology. I was trying to create it as an TransformedUnit with a Symbol (ideally `"\u212B"`). 

```java
Unit<Length> ANGSTROEM = new TransformedUnit<>("A", METRE, METRE, new RationalConverter(BigInteger.ONE, BigInteger.TEN.pow(10)));
Quantities.getQuantity(1, ANGSTROEM);
```
The conversion works fine but toString() does not return the expected result.

**Expected**: 1 A

**Actual**: 1 m/1.0E10

Is there another way to get this to work?

**Comment by keilw** [comment]
Yes there is, we have a draft for that in uom-systems-common: https://github.com/unitsofmeasurement/uom-systems/blob/master/common-java8/src/main/java/systems/uom/common/NonSI.java 
By calling ` public static final Unit<Length> ANGSTROM = addUnit(METRE.divide(10000000000L));
` (note there are multiple `addUnit()` variants, a few are optimized to use in `AbstractSystemOfUnits`) or similar, you will automatically call the `UnitFormat.label()` method which is necessary for all formatting. `TransformedUnit ` is no exception here right now, we may consider it in a future RI for JSR 385 (version 2.0) if it does not break compatibility with other Unit classes.

**Comment by cleberecht** [comment]
Thank you for the lighting-fast answer! I was confused on how the labeling would work - thanks for the clarification. For now I will use a static block for initialization.
``` java
public static final Unit<Length> ANGSTROEM = METRE.divide(10000000000L);
static {
    SimpleUnitFormat.getInstance().label(ANGSTROEM, "\u212B");
}
```
You may close this.

**Comment by keilw** [comment]
Great, thanks. I will close this one. I created a ticket for possible consideration in 2.0 but glad to help you on using 1.0 till then.

**Comment by keilw** [comment]
@cleberecht  Actually ANGSTROM (see https://en.wikipedia.org/wiki/%C3%85ngstr%C3%B6m where it is mentioned as alias or English version) already exists in si-units. The label is not set in si-units-java8, which I created https://github.com/unitsofmeasurement/si-units/issues/43 for. 
If you feel a TransformedUnit was more appropriate, please file an issue against si-units, but of course everyone may define their own units if they prefer.
