### ISSUE TITLE
TokenException when parsing `m^2` but not `m2`

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-se#200]
Hi, 
   I've been updating to the latest version of the unit of measurements and I'm having a little issue when I try to parse `m^2`. It works with `m2`. 

I use the default format service: 

```
UnitFormatService formatService = ServiceProvider.current().getUnitFormatService();
UnitFormat defaultFormatService = formatService.getUnitFormat();
Unit parsedUnit = defaultFormatService.parse("m");
```

In fact `m^2` is the representation of a "complex" unit we have already recognised in its parts (the prefix, the base and the exponent) and use its String representation to performa the normalisation with the `defaultFormatService`. We use `^` as a separator for the exponent. Here the idea is to support several cases and more complex units. It seems to be that the character `^` is not supported as separator / indicator of an exponent. Is there an ideal way to do so? 

Thank you in advance
Luca

**Comment by keilw** [comment]
`Bootstrap`? Is there a reason why you use an extremely old, non-final version of JSR 363/uom-se?

**Comment by lfoppiano** [comment]
Sorry I've made a mistake. I've corrected the initial comment.

**Comment by keilw** [comment]
The expression only works for SimpleUnitFormat, the others are stricter, and if you combine the mentioned modules, you get all of these available `ServiceProvider` extensions 
```
UCUMServiceProvider
systems.uom.common.internal.CommonServiceProvider@1e80bfe8
si.uom.impl.SIServiceProvider@66a29884
tec.uom.se.spi.DefaultServiceProvider@4769b07b
```

Leaving aside that only the UCUM one has a pretty printing name. You should see the current provider if you call something like `System.out.println(ServiceProvider.current());

The **current** `ServiceProvider` is not the same as the **default** `ServiceProvider` (as in provided by the implementation you're using) To use the `DefaultServiceProvider` you need to extend your code a bit
``` java
 ServiceProvider defaultProvider = ServiceProvider.current(); // just a fallback to avoid uninitialized variable
 for (ServiceProvider provider : ServiceProvider.available()) {
     if ("DefaultServiceProvider".equals(provider.getClass().getSimpleName())) {
         defaultProvider = provider;
         break;
     }
 }
UnitFormatService formatService = defaultProvider.getUnitFormatService();
UnitFormat defaultFormatService = formatService.getUnitFormat();
Unit parsedUnit = defaultFormatService.parse("m^2");
```
Then it will work. 

Sorry if this may sound a bit complex. We could add further methods in `ServiceProvider` in a future version of the API allowing to get one by name (although the name would have to be well-defined then) but the general idea of having a different current provider is not so different from say CDI when you call it in different environments or layers of the container.
`

**Comment by lfoppiano** [comment]
Actually I have another question, would be possible to provide, when available the product of units directly?

**Comment by keilw** [comment]
Can you explain that in a little more detail? Products of units e.g. `METRE.multiply(METRE)` are available and usable.

**Comment by lfoppiano** [comment]
Perhaps our use case is a bit special: we get free text where the units are sometimes encoded in strange ways, given the fact the data comes from PDF sometimes there is noise, spaces, missing characters and so on. 

We have a ML tagging model to identify the unit, and decompose it in products of (base, power and exponent) when possible  (this does't work for example for imperial units). 

Once we have the structured data, we use the unit of measurement for the normalisation, but to do that we transform our structure in a well formed string and pass it to the parse() method. I was just wondering if having a method accepting some sort of structured unit (I'm not sure we can generate METRE.multiply(METRE) in a non programmatic way) instead of re-parsing from the string.

I hope I've explained myself. 

Thanks
Luca 

Let's supposed you have `ml/(km · min)` they can be rewritten as product of units `ml * km^-1 * min^-1`  this is a fairly standardised way and I believe it would simplify the parsing.

**Comment by desruisseaux** [comment]
You may also give a try to [seshat](https://github.com/unitsofmeasurement/seshat), which is lenient on unit parsing: it accepts both `ml/(km⋅min)` and `ml*km^-1*min^-1` (not always desirable - sometime it is good to be strict - but in your use case it may be convenient). Current version will produce a strange unit however: `1.6666666666666667E-11⋅m²∕s` - numerically equivalent (I think - I did not checked) but maybe not what users would expect. We do not have perfect implementation, which is why there is many you can try.

**Comment by keilw** [comment]
@lfoppiano If you work with uom-se only, please give it a try. Seshat also has a slightly broader `SystemOfUnit` implementation, being less strict in separating SI, Non-SI and other units from one another. A bit like ICU4J and the [unicode](https://github.com/unitsofmeasurement/uom-systems/tree/master/unicode-java8) modules we got for uom-se and Indriya. If that's the idea, that would be fine.

**Comment by lfoppiano** [comment]
Thanks @desruisseaux and @keilw for the suggestions.

**Comment by lfoppiano** [comment]
@desruisseaux I've noticed that seshat is working only with Java 10. 
Do you think it would be possible, with some minimal changes, to have it working in java 8?

**Comment by desruisseaux** [comment]
Yes, we can easily create a "JDK8" branch with a port of Seshat to Java 8. I was basically waiting to see if there is a need for that.

**Comment by lfoppiano** [comment]
@desruisseaux if it's not too much work. I've opened a ticket about it on the project.
