### ISSUE TITLE
What happened to BIT?

### ISSUE THREAD

**Issue by astubbs** [unitsofmeasurement/uom-se#206]
Trying to track this down - what' the story / background information with what's happening with BIT? 

https://github.com/unitsofmeasurement/uom-se/commit/5e5993f20968c92755b74d84405f47b6585bae5c#diff-7f89055164ef912cc0a19b3aad48a6ffR214

Hmm, also found this:
https://github.com/unitsofmeasurement/uom-demos/blob/c710345f50f798ba4a4670a3b3b9878ca6432e94/console/systems/unicode/src/main/java/tech/uom/demo/types/enums/BitUnit.java

**Comment by keilw** [comment]
uom-se is no longer actively maintained, only serious bugs or vulnerabilities, is there a reason you created the ticket here?

**Comment by astubbs** [comment]
Nope, just on the hunt, new to this and a little confused ;)

Could you point me in the direction of the BIT?

A note relaying what you said here in the readme at the top of the uom-se front page might be good :)

**Comment by astubbs** [comment]
Ah-ha! https://github.com/unitsofmeasurement/uom-systems/blob/c0aa6fb1bebfd7a11a67def77a0d67fe74a527e5/ucum/src/main/java/systems/uom/ucum/UCUM.java#L903

So uom-systems is the main project now?

**Comment by keilw** [comment]
It depends, but for units like BIT yes. The RI is https://unitsofmeasurement.github.io/indriya/

**Comment by astubbs** [comment]
Ok cool, thanks. And I found ButUnit here in your demo app project. Any plans to extact that into a usable library somewhere? I had a look but it seems the tech.uom.demo.console.systems artifact isn't available in repo1?

https://github.com/unitsofmeasurement/uom-demos/blob/c710345f50f798ba4a4670a3b3b9878ca6432e94/console/systems/unicode/src/main/java/tech/uom/demo/types/enums/BitUnit.java#L56

**Comment by keilw** [comment]
Since it's not an SI unit, the only places we support it already are [Unicode](https://github.com/unitsofmeasurement/uom-systems/tree/master/unicode/src/main/java/systems/uom/unicode) and [UCUM](https://github.com/unitsofmeasurement/uom-systems/tree/master/ucum). Please find them there, closing the ticket because it already exists.
