### ISSUE TITLE
Upgrade :maven-surefire-plugin:2.22.0

### ISSUE THREAD

**Issue by otaviojava** [unitsofmeasurement/uom-se#209]
Hello everyone, question.

Can we update this plugin to version 2.22.0?
This plugin is important to run and compile our code with JDK 11.
ps: I won't change the minimum requirement the point is enabled to run on the Java 11 as well.

**Comment by keilw** [comment]
No, the minimal JDK is 8 and even Indriya won't require 11 to run. The API already uses the Multi-release JAR feature of Java 9+ but the minimal version is still 8 to run it. Will check if 2.22.0 is possible, but there was a major problem with Jacoco that still seems unsolved, therefore we may have to keep the one that is there.

**Comment by keilw** [comment]
It seems to work but it needs an upgrade of the Parent POM 1.x as well.
