### ISSUE TITLE
Stackoverflow during QuantityDimension.multiply

### ISSUE THREAD

**Issue by sebastian-peter** [unitsofmeasurement/uom-se#216]
When calling `QuantityDimension#multiply(Dimension that)` with a `that` of a different type than `QuantityDimension`, an infinite recursion is triggered.

I guess that's because while the documentation of this method states, `that.multiply(this)` should be called in this case, in actuality `this.multiply(that)` is called.

**Comment by andi-huber** [comment]
Thanks for spotting this! Same bug is also in the corresponding `divide` method.

**Comment by keilw** [comment]
Thanks for the clarification, is it only in uom-se and Indriya does not face any of that because of a different implementation?

**Comment by keilw** [comment]
@andi-huber Has Indriya ever fixed that? I hope we can finish the Bintray switch-over plus 2 bugs (where this one sounds more critical, the other #215 is merely an inconvenience with one particular unit) and release 1.0.11 eventually before archiving the old SE release for good?

**Comment by andi-huber** [comment]
Hi @keilw - I believe this on does not affect Indriya. I don't see a connection. Apparently Indriya introduced a `DimensionalModel`, which handles _dimensionality_ differently.

**Comment by keilw** [comment]
@andi-huber I believe it must have been there in uom-se because they have similar foundations but maybe it was not so actively used back then. Do you see a realistic and not too complex solution to this here, otherwise we should probably just recommend upgrading to Indriya, because if there's now a problem in the JDK, even Java 11 most bugs were not backported either but developers must migrate to 13 or 15. We could do the same if the fix is not possible or would require a lot of effort we don't have resources for.

**Comment by keilw** [comment]
@sebastian-peter I know this ticket is a bit old, hope you still follow it? Did you create your own implementation of either `DimensionalModel`,  `Dimension` or both?
@andi-huber What I noticed and I don't believe it can be so much different in Indriya unless other changes brought that, in the `divide()` method no `(that instanceof QuantityDimension)` check is done, so maybe that explains why this happens for different implementations.
Do you think we could create a minimalistic implementation a bit like the one in [unit-api](https://github.com/unitsofmeasurement/unit-api) maybe and test in a JUnit test, if it can be replicated, solving it if it does?

**Comment by andi-huber** [comment]
@keilw - I was wrong, it does affects Indriya. You are right, it seems the relevant code lives on in Indriya's `UnitDimension`. Think we can fix that.

**Comment by keilw** [comment]
Cool, so you plan to fix that here based on https://github.com/unitsofmeasurement/indriya/issues/339?

**Comment by andi-huber** [comment]
Not planning to, no.

**Comment by keilw** [comment]
Ok then I might do it, seems a low-hanging fruit, but for further changes or improvements migrating to Indriya is highly recommended.
