### ISSUE TITLE
Integration with Date and Measuarement of Time that already exist in Java.

### ISSUE THREAD

**Issue by otaviojava** [unitsofmeasurement/uom-se#39]
# Motivation:

One of Quantities that are used in Measure API is Time and is important that API works with the way that has in Java SE 8 or above. The proposal of this enhancement

### Goal:

* Work with java.util.Date
* Work with new Java Date API (JSR 310)

### Not Goal:

* With java.util.concurrent.TimeUnit or
* JavaFX Duration

### Qualified:

* tec.uom.se.quantity, possibly
* tec.uom.se.unit or tec.uom.se.util

**Comment by keilw** [comment]
Is this done?

**Comment by otaviojava** [comment]
Yes

**Comment by keilw** [comment]
Thanks, closing this now then.
