### ISSUE TITLE
Clarify behavior of getSymbol() by a TransformedUnit

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#54]
See https://java.net/jira/browse/UNITSOFMEASUREMENT-109

**Comment by magnonasc** [comment]
So, I guess you never fixed this one, right?

**Comment by keilw** [comment]
So far there was nothing to fix. The behavior of a `TransformedUnit` is defined through additional methods like `getConverter()` that only exist in a slightly different way on the API level (e.g. `getConverterTo()`) If the UCUM formatter has a problem by not taking getConverter into consideration for a `TransformedUnit`, maybe that is something to look into.

**Comment by magnonasc** [comment]
It's a little bit confused to me, because I think `toString()` should reflect `getSymbol()`, and in the cases I've seen the inverse, `toString()` working exactly how I think `getSymbol()` should be.

**Comment by keilw** [comment]
However `getSymbol()` exists in far fewer cases than the label or operation/driven mechanism to get the string representation. For most products of other units `getSymbol()` is empty or `null `by definition. http://unitsofmeasurement.github.io/unit-api/site/apidocs/javax/measure/Unit.html#getSymbol()

**Comment by magnonasc** [comment]
So is it safe to use `toString()` as a representation of the unit?

**Comment by keilw** [comment]
Yes, while` getSymbol()` may be null `toString()` takes other information like the operation or an explicit `label()` call for this unit. If there was no label() call, then you may see a raw result like "m/12345" but that is because AbstractUnit uses the basic formatter. If a specialized UnitFormat is required, for a particular unit system like UCUM, then toString() may differ.

**Comment by keilw** [comment]
Btw, at least in a normal text editor classes like `UCUMFormat` lose most intents, e.g. a switch statement ends up unintended. In GitHub viewer it seems fine.

**Comment by keilw** [comment]
There are certain assumptions, e.g. about the concrete subtype of a `Unit` or `UnitConverter` involved. `getBaseUnits()` was once called `getProductUnits()`. It may have been slightly unlucky because it got detached from e.g. its purpose for a `ProductUnit`. The exponent in the `Map` is an `Integer`.  This limits the units you can put into this chain a bit. E.g. a `TransformedUnit` with a `LogConverter` or a few others do not have the same information to put there. In theory picking a few particular ones, e.g. `MultiplyConverter`, but  I am not sure, if this was possible without affecting more than just `UCUMFormat`? If such patch of `getBaseUnits()` for a few Unit classes like `TransformedUnit `was worth a shot, it could require an actual MR of the JSR. Any such modification is only possible for RI and other relevant implementations. Until then looking for e.g. a type like `TransformedUnit `and using its `getConverter()` method for formatting looks like the safer and more sensible approach.
