### ISSUE TITLE
Consolidate message bundle files

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#95]
The 2 sets of message bundle properties in ../format and ../internal/format serve 2 different UnitFormat implementations. At least the locale-agnostic EBNFUnitFormat should not require more than one properties file. Translations where they don't exist there already should be moved to the one serving LocalUnitFormat. And strings for the default locale should be in sync between the two of them.

**Comment by JeanPhiPhi** [comment]
Displaying message is a matter of UI. Translation must be done there. Base "toString" display is for debug only, not locale dependent.

**Comment by keilw** [comment]
If you use a locale-sensitive UnitFormat implementation like LocalUnitFormat, then it will take the Locale into consideration. All others (even if backed by resource bundles and a "pseudo-locale" e.g. extensions like UCUM) usually won't or as in the RI are even fully unaware of a locale.

**Comment by JeanPhiPhi** [comment]
As long as that kind of "format" is not part of the core implementation it's fine :)

**Comment by keilw** [comment]
I don't see a need for that. E.g. uom-se also supports interaction with java.time (since that's part of OpenJDK) hence supporting the Java SE Locale in uom-se, while not doing so in the (ME-compatible) RI sounds fine. Other specific formatters like UCUM come with a dedicated UCUM module, but it would overcomplicate things if we put something that works with Java SE/OpenJDK into yet another package or module. uom-se may in future be modularized, but I think we might leave that until Jigsaw is final.

**Comment by keilw** [comment]
The purpose of the task is, that using a "Pseudo-Locale" EBNFUnitFormat at most needs one properties file. While LocalUnitFormat will have more depending on the number of locales/languages.

**Comment by keilw** [comment]
In fact, since there is only one Properties file for EBNFUnitFormat, this is done.

**Comment by JeanPhiPhi** [comment]
As you wish. But keep in mind you cannot control what a UI needs to perform. As a simple example, parsing "12 ms" or "12 millis" or simply "12" (implying ms as default) can be specified as the same for a UI.
Trying to translate / parse in core UOM goes too far IMHO ;)

**Comment by keilw** [comment]
Unicode CLDR http://cldr.unicode.org/ does exactly that. For a number of units not too different from those se support in uom-se/unit-ri right now. JavaSE/JDK since at least Java 7 is very compatible with CLDR regarding its Locale/Calendar/Date and Currency support. The "core" JDK as such has no use for its rich multi-lingual Units DB while we certainly might. Unicode has done all that, including pluralization. Whether uom-se or alternate implementations (like Eclipse UOMo which already builds on ICU4J) make full use of CLDR, I can't say at the moment, but I would not outrule it for any Java SE implementation (for ME it's simply too big, just take java.time and Timezone data taking more than 2MB of the JDK alone ;-) )

**Comment by JeanPhiPhi** [comment]
...and far from core UOM business! This is not a matter of Java SE implementation or memory consumption. This is just a matter of what UOM is for. To me UOM deals with quantities and units. A string display is not a quantity; it's just a representation of it.

Else, to be consistent, you would have to provide quantity.add(String) and so on :)

I'm very happy that uom-se does not rely on ICU4J or similar libs (which lead us to patch UOMo).

**Comment by keilw** [comment]
quantity.add(String) does not make sense. There are arithmetic operations like quantity.add(quantity), while adding a string (in a Locale-context or not, that's up to the implementation) to a Unit is done via UnitFormat.label(Unit, String). As of now, we see no need to directly use ICU4J in uom-se. At JavaOne we had first discussions with some OpenJDK committers to e.g. Project Kona (http://openjdk.java.net/projects/kona/) where especially with some already existing modules like COAP uom-se could be quite beneficial. It may in the future lead to an "jdk-uom" project of some sort, either under Kona or elsewhere (just take Device I/O). And while importing CLDR data and having taken some inspirations from it, JDK does not directly use ICU4J either. Hence we tend to do similar in uom-se to allow donation to OpenJDK if there's demand for it. Other implementations like UOMo will probably stick to ICU4J, unless we find it more beneficial to directly use e.g. unit-ri or uom-se (or some other future implementation)

**Comment by JeanPhiPhi** [comment]
Ok. I guess this issue is too close from an implementation perspective.

So I opened a new "overall" issue: #102
