### ISSUE TITLE
Should all abstract base classes implement Serializable?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#98]
At the moment AbstractUnit implements Serializable, while at least AbstractConverter doesn't. For converters this is done by concrete classes. Hence a sub-class extending the abstract base class may have to do this by itself.

Somewhat related to https://github.com/unitsofmeasurement/uom-se/issues/96

**Comment by ceefour** [comment]
:+1: for making SE port / RI have Serializable support.

If the APIs can't have Serializable well I guess we have to live with it, but please make abstracts Serializable.

**Comment by ceefour** [comment]
Isn't this repo for "JavaSE 8 and up"?

**Comment by keilw** [comment]
Yes

**Comment by ceefour** [comment]
Thank you :)
